name: kept
description: Do what you say you will do.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: false

flutter_native_splash:
  color: "#E8EDE8"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/