// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ydnsGOb2J6Fwipm30FE14Kj2NSSQqy4',
    appId: '1:160642501661:web:01cccb2f3c33e2c3058af4',
    messagingSenderId: '160642501661',
    projectId: 'riverpod-learn-auth',
    authDomain: 'riverpod-learn-auth.firebaseapp.com',
    storageBucket: 'riverpod-learn-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEJkJV2jYinHqNNDURyL_NTR9Vs5gZqNY',
    appId: '1:160642501661:android:ef0fd440d6480e38058af4',
    messagingSenderId: '160642501661',
    projectId: 'riverpod-learn-auth',
    storageBucket: 'riverpod-learn-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZ4R9tRHB116oWqCv2tPiCcy35nv-zK4',
    appId: '1:160642501661:ios:cc59054fc6f4addd058af4',
    messagingSenderId: '160642501661',
    projectId: 'riverpod-learn-auth',
    storageBucket: 'riverpod-learn-auth.firebasestorage.app',
    iosBundleId: 'com.example.kept',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZ4R9tRHB116oWqCv2tPiCcy35nv-zK4',
    appId: '1:160642501661:ios:cc59054fc6f4addd058af4',
    messagingSenderId: '160642501661',
    projectId: 'riverpod-learn-auth',
    storageBucket: 'riverpod-learn-auth.firebasestorage.app',
    iosBundleId: 'com.example.kept',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ydnsGOb2J6Fwipm30FE14Kj2NSSQqy4',
    appId: '1:160642501661:web:fc13367fb9499220058af4',
    messagingSenderId: '160642501661',
    projectId: 'riverpod-learn-auth',
    authDomain: 'riverpod-learn-auth.firebaseapp.com',
    storageBucket: 'riverpod-learn-auth.firebasestorage.app',
  );
}
